version: "3"

services:
  app:
    container_name: demo.acorexui.com
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3006:80"
    environment:
      - NODE_ENV=production
      - PORT=3006
